### ISSUE TITLE
Tidyverse ease and the future of R

### ISSUE THREAD

**Issue by Nelson-Gon** [matloff/TidyverseSkeptic#20]

**Comment by iqis** [comment]
`...and is more pythonic...`
What is being discussed here has nothing whatsoever to do with Python. 
Jussayin.

**Comment by Nelson-Gon** [comment]
Please feel free to open a new issue. I find it odd that you quote one sentence and that too only partially. Here's the full sentence in case you missed it:
"In terms of use, I think the tidyverse is simpler to use for a non-programmer and is more pythonic in the sense that one can easily link a function's name to what it does"
I do not understand why you had to use "jussayin" except perhaps to be unnecessarily rude. Either way, please feel free to open an issue and discuss what you feel is more relevant. What I wrote was my opinion on the matter(then).

**Comment by Nelson-Gon** [comment]
Deleted because your comment was really offensive.
