### ISSUE TITLE
Translation and promotion of the article

### ISSUE THREAD

**Issue by boltomli** [matloff/TidyverseSkeptic#22]
The article is a good example of open discussion over education as a point of view. I have been struggling through base and tidy for most of the time.

Since there's no explicit license attached, I assume this is copyrighted material. May I translate the article to Chinese in a Fork? And perhaps promote to R & stats forum such as <https://github.com/cosname/cosx.org/issues>?

**Comment by matloff** [comment]
Feel free to translate; please give me a URL when you post it. Posting to COS is fine too, though the response may be negative. :-)

**Comment by boltomli** [comment]
Here's the translated branch <https://github.com/boltomli/TidyverseSkeptic> :)

**Comment by matloff** [comment]
Thanks very much! That was a lot of work on your part. I glanced through it, good job!

**Comment by boltomli** [comment]
It's posted to COS as well, the link <https://cosx.org/2020/10/alternative-view-tidyverse-r/> (in Chinese). Thank you for the insights!

**Comment by matloff** [comment]
Thanks so much! That really was a ton of work for you. I read through the first few paragraphs, and the translation is excellent.
