### ISSUE TITLE
Where Are We Now, and Where Should We Be Going? typo/wrong package

### ISSUE THREAD

**Issue by JulianCollins** [matloff/TidyverseSkeptic#30]
Also in 2019, RStudio stopped viewing data.table as a rival, and announced the release of dtplyr, a Tidy-syntax front end to _dplyr_.

should be:

Also in 2019, RStudio stopped viewing data.table as a rival, and announced the release of dtplyr, a Tidy-syntax front end to **data.table.**

**Comment by matloff** [comment]
Fixed, thanks.
